services:
  chromadb:
    image: ghcr.io/chroma-core/chroma:latest
    container_name: chromadb
    ports:
      - "7001:8000"
    restart: unless-stopped
    volumes:
      - chromadb_data:/chroma

  backend:
    build:
      context: ./srcs/backend_FastAPI 
      dockerfile: Dockerfile
    container_name: rag-backend
    volumes:
      - ./srcs/backend_FastAPI:/app
    depends_on:
      - chromadb
    environment:
      - CHROMA_HOST=chromadb
      - CHROMA_PORT=8000
    ports:
      - "8501:8501" 
  
  llm:
    build:
      context: ./srcs/Docker_llm
      dockerfile: Dockerfile
    container_name: Docker_llm
    volumes:
      - ./srcs/Docker_llm:/app
    depends_on:
      - backend
    ports:
      - "11434:11434"

  backend2:
    build:
      context: .
      dockerfile: ./srcs/backend_Fiber/Dockerfile
    container_name: backend_go
    ports:
      - "8080:8080" 
    env_file:
      - .env
    volumes: 
      - ./srcs/backend_Fiber:/app
    # depends_on:
    #   - chromadb
    restart: unless-stopped
  

volumes:
  chromadb_data:
